spring:
  application:
    name: ch9_1
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/sbdt_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: 1234

    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-sbdt_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: true
  sql:
    init:
      mode: always

authorization:
  key: dXNlcjoyOTk1ZWZkYi03MjM3LTQ3NzAtOGY4OC1lYjZjZDE1YTcyYTU=